#!/bin/bash
SCRIPT_NAME=all-shit.sh
MAIN_SCRIPT=openshit.sh
PREINSTALL_SCRIPT=pre-install.sh

#services
SERVICE_DATABASE=mysql
SERVICE_MESSAGE_QUEUE=rabbitmq
SERVICE_OPENSTACK_IDENTITY=keystone
SERVICE_OPENSTACK_IMAGE=glance
SERVICE_OPENSTACK_COMPUTE=nova
SERVICE_OPENSTACK_BLOCK_STORAGE=cinder
SERVICE_OPENSTACK_NETWORK=nova-network
SERVICE_OPENSTACK_DASHBOARD=dashboard

#service list
SERVICES="\
  $SERVICE_DATABASE \
  $SERVICE_MESSAGE_QUEUE \
  $SERVICE_OPENSTACK_IDENTITY \
  $SERVICE_OPENSTACK_IMAGE \
  $SERVICE_OPENSTACK_COMPUTE \
  $SERVICE_OPENSTACK_BLOCK_STORAGE \
  $SERVICE_OPENSTACK_NETWORK \
  "

SERVICE_HAS_DATABASE="\
  $SERVICE_OPENSTACK_IDENTITY \
  $SERVICE_OPENSTACK_IMAGE \
  $SERVICE_OPENSTACK_COMPUTE \
  $SERVICE_OPENSTACK_BLOCK_STORAGE \
  "

COMPONENTS="\
  $SERVICE_OPENSTACK_DASHBOARD
  "
