#!/bin/bash
MYSQL_CONFIG=/etc/mysql/my.cnf
SUB_SCRIPT_NAME=mysql

help()
{
  echo "usage: $SCRIPT_NAME $SUB_SCRIPT_NAME <init|config|start|stop|restart>"
}

do_config()
{
  add_args_to_section $MYSQL_CONFIG "\[mysqld\]" \
    "innodb_file_per_table" \
    "default-storage-engine" \
    "collation-server" \
    "init-connect" \
    "character-set-server"
  set_conf_arg "default-storage-engine" "default-storage-engine = InnoDB" $MYSQL_CONFIG
  set_conf_arg "collation-server" "collation-server = utf8_general_ci" $MYSQL_CONFIG
  set_conf_arg "init-connect" "init-connect = 'SET NAMES utf8'" $MYSQL_CONFIG
  set_conf_arg "character-set-server" "character-set-server = utf8" $MYSQL_CONFIG

  do_service restart
}

do_service()
{
  sudo /etc/init.d/mysql $1
}

if [ $# -lt 2 ]; then
  help
elif [ "config" = $2 -o "init" = $2 ]; then
  do_config
elif [ "start" = $2 -o "stop" = $2 -o "restart" = $2 ]; then
  do_service $2
else
  help
fi
