#!/bin/bash
SUB_SCRIPT_NAME=rabbitmq
help()
{
  echo "usage: $SCRIPT_NAME $SUB_SCRIPT_NAME <config|start|stop|restart>"
}

do_config()
{
  echo "SET_RABBITMQ_PASS=$SET_RABBITMQ_PASS"
  sudo rabbitmqctl change_password guest $SET_RABBITMQ_PASS
}

do_service()
{
  sudo service rabbitmq-server $1
}

if [ $# -lt 2 ]; then
  help
elif [ "config" = $2 ]; then
  do_config
elif [ "start" = $2 -o "stop" = $2 -o "restart" = $2 ]; then
  do_service $2
else
  help
fi
