#!/bin/bash
SERVICE_LIST="all"
PACKAGE_LIST="all"

# args: service-list
# env: ACTION
invoke_service_list()
{
  for item in $@;
  do
    echo "${ACTION}: ${item}"
    invoke_service $item $ACTION
  done
}

func_service()
{
  invoke_service_list $SERVICES
}

func_package()
{
  invoke_service_list $SERVICES $COMPONENTS
}

func_config()
{
  invoke_service_list $SERVICES
}

func_clean()
{
  invoke_service_list $SERVICES_HAS_DATABASE
}
