#!/bin/bash
import $SERVICE_OPENSTACK_IDENTITY

PACKAGE_LIST="cinder-api cinder-scheduler python-cinderclient cinder-volume"
SERVICE_LIST="cinder-scheduler cinder-api cinder-volume tgt"
CINDER_CONF_FILE=/etc/cinder/cinder.conf

func_cinder_clean()
{
  load_admin_env
  delete_user
  $SERVICE_DATABASE"_drop" $SERVICE_NAME
}

func_cinder_config()
{
  $SERVICE_DATABASE"_create" $SERVICE_NAME $SET_CINDER_DBPASS
  load_admin_env
  delete_user
  create_user
  edit_conf
  sudo su -s /bin/sh -c "cinder-manage db sync" $SERVICE_NAME
  func_service restart
}

edit_conf()
{
  #config CINDER_CONF_FILE
  add_args_to_section $CINDER_CONF_FILE "\[DEFAULT\]" "glance_host" "my_ip"

  set_conf_arg "my_ip" "my_ip = $SET_CINDER_IP" $CINDER_CONF_FILE
  set_conf_arg "glance_host" "glance_host = $SET_CINDER_IP" $CINDER_CONF_FILE

  $SERVICE_DATABASE"_set_conf" $SERVICE_NAME $SET_CINDER_DBPASS $CINDER_CONF_FILE
  $SERVICE_OPENSTACK_IDENTITY"_set_conf" $SERVICE_NAME $SET_CINDER_PASS $CINDER_CONF_FILE
  $SERVICE_MESSAGE_QUEUE"_set_rpc_config" $CINDER_CONF_FILE
}

create_user()
{
  $SERVICE_OPENSTACK_IDENTITY"_create_user_service" $SERVICE_NAME $SET_CINDER_PASS volume
  $SERVICE_OPENSTACK_IDENTITY"_create_endpoint" $SERVICE_NAME \
    http://$SET_CINDER_IP:8776/v1/%\(tenant_id\)s \
    http://$SET_CINDER_IP:8776/v1/%\(tenant_id\)s \
    http://$SET_CINDER_IP:8776/v1/%\(tenant_id\)s
}

delete_user()
{
  $SERVICE_OPENSTACK_IDENTITY"_delete_user_service" $SERVICE_NAME
}
