#!/bin/bash
import $SERVICE_OPENSTACK_IDENTITY

SERVICE_LIST="glance-registry glance-api"
PACKAGE_LIST="glance python-glanceclient"
GLANCE_API_CONF_FILE=/etc/glance/glance-api.conf
GLANCE_REGISTRY_CONF=/etc/glance/glance-registry.conf

func_glance_clean()
{
  delete_user
  $SERVICE_DATABASE"_drop" $SERVICE_NAME
}

func_glance_config()
{
  $SERVICE_DATABASE"_create" $SERVICE_NAME $SET_GLANCE_DBPASS
  delete_user
  create_user
  edit_conf
  sudo su -s /bin/sh -c "glance-manage db_sync" $SERVICE_NAME
  func_service restart
}

edit_conf()
{
  #config $GLANCE_API_CONFIG_FILE
  $SERVICE_DATABASE"_set_conf" $SERVICE_NAME $SET_GLANCE_DBPASS $GLANCE_API_CONF_FILE
  $SERVICE_OPENSTACK_IDENTITY"_set_conf" $SERVICE_NAME $SET_GLANCE_DBPASS $GLANCE_API_CONF_FILE

  #config $GLANCE_REGISTRY_CONF
  $SERVICE_DATABASE"_set_conf" $SERVICE_NAME $SET_GLANCE_DBPASS $GLANCE_REGISTRY_CONF
  $SERVICE_OPENSTACK_IDENTITY"_set_conf" $SERVICE_NAME $SET_GLANCE_DBPASS $GLANCE_REGISTRY_CONF
}

create_user()
{
  load_admin_env
  $SERVICE_OPENSTACK_IDENTITY"_create_user_service" $SERVICE_NAME $SET_GLANCE_DBPASS image
  $SERVICE_OPENSTACK_IDENTITY"_create_endpoint" $SERVICE_NAME \
    "http://$SET_GLANCE_IP:9292" \
    "http://$SET_GLANCE_IP:9292" \
    "http://$SET_GLANCE_IP:9292"
}

delete_user()
{
  load_admin_env
  $SERVICE_OPENSTACK_IDENTITY"_delete_user_service" $SERVICE_NAME
}
