#!/bin/bash
import $SERVICE_OPENSTACK_IDENTITY

SERVICE_LIST="glance-registry glance-api"
PACKAGE_LIST="glance python-glanceclient"
GLANCE_API_CONF_FILE=/etc/glance/glance-api.conf
GLANCE_REGISTRY_CONF_FILE=/etc/glance/glance-registry.conf

func_glance_clean()
{
  load_admin_env
  delete_user
  $SERVICE_DATABASE"_drop" $SERVICE_NAME
}

func_glance_config()
{
  #edif conf
  $SERVICE_DATABASE"_create" $SERVICE_NAME $SET_GLANCE_DBPASS

  edit_conf

  #delete user
  load_admin_env
  delete_user

  #create_user
  create_user

  sudo su -s /bin/sh -c "glance-manage db_sync" $SERVICE_NAME
  func_service restart
}

edit_conf()
{
  #config $GLANCE_API_CONFIG_FILE
  edit_config_file $GLANCE_API_CONF_FILE edit_glance_api_conf

  #config $GLANCE_REGISTRY_CONF
  edit_config_file $GLANCE_REGISTRY_CONF_FILE edit_glance_registry_conf
}

edit_glance_api_conf()
{
  $SERVICE_OPENSTACK_IDENTITY"_edit_conf" $SERVICE_NAME $SET_GLANCE_PASS
  $SERVICE_DATABASE"_edit_conf" $SERVICE_NAME $SET_GLANCE_DBPASS
  echo "[paste_deploy]"
  echo "flavor = keystone"
  echo "[DEFAULT]"
  echo "verbose = True"
}

edit_glance_registry_conf()
{
  $SERVICE_OPENSTACK_IDENTITY"_edit_conf" $SERVICE_NAME $SET_GLANCE_PASS
  $SERVICE_DATABASE"_edit_conf" $SERVICE_NAME $SET_GLANCE_DBPASS
  echo "[paste_deploy]"
  echo "flavor = keystone"
  echo "[DEFAULT]"
  echo "verbose = True"
}

delete_user()
{
  $SERVICE_OPENSTACK_IDENTITY"_delete_user" $SERVICE_NAME
  $SERVICE_OPENSTACK_IDENTITY"_delete_service" $SERVICE_NAME
}

create_user()
{
  $SERVICE_OPENSTACK_IDENTITY"_create_user" $SERVICE_NAME $SET_GLANCE_PASS
  $SERVICE_OPENSTACK_IDENTITY"_create_service" $SERVICE_NAME image
  $SERVICE_OPENSTACK_IDENTITY"_create_endpoint" $SERVICE_NAME \
    http://$SET_GLANCE_IP:9292 \
    http://$SET_GLANCE_IP:9292 \
    http://$SET_GLANCE_IP:9292
}
