#!/bin/bash
KEYSTONE_CONF_FILE=/etc/keystone/keystone.conf
PACKAGES="keystone python-keystoneclient"

help()
{
  echo "usage: $SCRIPT_NAME $SERVICE_NAME <install|download|uninstall|clean|clean-expired|config|start|stop|restart>"
}

clean()
{
  delete_user
  drop_database $SERVICE_NAME
}

service()
{
  sudo service keystone $1
}

clean_expired_token()
{
  (crontab -l -u keystone 2>&1 | grep -q token_flush) || \
  echo '@hourly /usr/bin/keystone-manage token_flush >/var/log/keystone/keystone-tokenflush.log 2>&1' \
  >> /var/spool/cron/crontabs/keystone
}

config()
{
  set_database $SERVICE_NAME $SET_KEYSTONE_DBPASS
  edit_conf
  sudo su -s /bin/sh -c "keystone-manage db_sync" $SERVICE_NAME
  service restart
  echo "Waiting for service keystone start..."
  sleep 5
  source $SERVICE_ENV_FILE
  delete_user
  create_user
  source $ADMIN_ENV_FILE
}

edit_conf()
{
  set_conf_arg "admin_token" "admin_token=${SET_OS_SERVICE_TOKEN}" $KEYSTONE_CONF_FILE
  set_conf_arg "connection" "connection=mysql://$SERVICE_NAME:$SET_KEYSTONE_DBPASS@$SET_CONTROLLER_IP:$SET_MYSQL_PORT/$SERVICE_NAME" $KEYSTONE_CONF_FILE
  set_conf_arg "verbose" "verbose=True" $KEYSTONE_CONF_FILE
}

create_user()
{
  keystone tenant-create --name $SET_KEYSTONE_ADMIN_TENANT --description "${SET_KEYSTONE_ADMIN} Tenant"
  keystone user-create --name $SET_KEYSTONE_ADMIN --pass $SET_KEYSTONE_ADMIN_PASS --email $SET_YOUR_EMAIL
  keystone role-create --name $SET_KEYSTONE_ADMIN_ROLE
  keystone user-role-add --tenant $SET_KEYSTONE_ADMIN_TENANT --user $SET_KEYSTONE_ADMIN --role $SET_KEYSTONE_ADMIN_ROLE
  keystone role-create --name _member_
  keystone user-role-add --tenant $SET_KEYSTONE_ADMIN_TENANT --user $SET_KEYSTONE_ADMIN --role _member_

  keystone tenant-create --name service --description "Service Tenant"
  keystone service-create --name $SERVICE_NAME --type identity --description "OpenStack Identity"
  keystone endpoint-create \
  --service-id $(keystone service-list | awk '/ identity / {print $2}') \
  --publicurl http://$SET_CONTROLLER_IP:5000/v2.0 \
  --internalurl http://$SET_CONTROLLER_IP:5000/v2.0 \
  --adminurl http://$SET_CONTROLLER_IP:35357/v2.0 \
  --region regionOne
}

delete_user()
{
  keystone user-delete $SET_KEYSTONE_ADMIN
  keystone service-delete $SERVICE_NAME
  keystone tenant-delete $SET_KEYSTONE_ADMIN_TENANT
  keystone tenant-delete service
  keystone role-delete $SET_KEYSTONE_ADMIN_ROLE
  keystone role-delete _member_
}

if [ $# -lt 2 ]; then
  help
elif [ "clean" = $2 ]; then
  clean
elif [ "config" = $2 ]; then
  config
elif [ "clean-expired" = $2 ]; then
  clean_expired_token
elif [ "start" = $2 -o "stop" = $2 -o "restart" = $2 ]; then
  service $2
elif [ "install" = $2 ]; then
  install $PACKAGES
elif [ "uninstall" = $2 ]; then
  uninstall $PACKAGES
elif [ "download" = $2 ]; then
  download $PACKAGES
else
  help
fi
