#!/bin/bash
MYSQL_CONFIG=/etc/mysql/my.cnf
PACKAGES="mariadb-server python-mysqldb"

help()
{
  echo "usage: $SCRIPT_NAME $SERVICE_NAME <install|download|uninstall|config|start|stop|restart>"
}

config()
{
  edit_conf
  service restart
}

service()
{
  sudo /etc/init.d/mysql $1
}

edit_conf()
{
  add_args_to_section $MYSQL_CONFIG "\[mysqld\]" \
    "innodb_file_per_table" \
    "default-storage-engine" \
    "collation-server" \
    "init-connect" \
    "character-set-server"
  set_conf_arg "default-storage-engine" "default-storage-engine = InnoDB" $MYSQL_CONFIG
  set_conf_arg "collation-server" "collation-server = utf8_general_ci" $MYSQL_CONFIG
  set_conf_arg "init-connect" "init-connect = 'SET NAMES utf8'" $MYSQL_CONFIG
  set_conf_arg "character-set-server" "character-set-server = utf8" $MYSQL_CONFIG
}

if [ $# -lt 2 ]; then
  help
elif [ "config" = $2 ]; then
  config
elif [ "start" = $2 -o "stop" = $2 -o "restart" = $2 ]; then
  service $2
elif [  "install" = $2 ]; then
  install $PACKAGES
elif [  "uninstall" = $2 ]; then
  uninstall $PACKAGES
elif [  "download" = $2 ]; then
  download $PACKAGES
else
  help
fi
