#!/bin/bash
PACKAGE_LIST="mariadb-server python-mysqldb"
SERVICE_LIST="mysql"
MYSQL_CONFIG=/etc/mysql/my.cnf

func_config()
{
  edit_conf
  func_service restart
}

func_service()
{
  sudo /etc/init.d/mysql $1
}

edit_conf()
{
  add_args_to_section $MYSQL_CONFIG "\[mysqld\]" \
    "innodb_file_per_table" \
    "default-storage-engine" \
    "collation-server" \
    "init-connect" \
    "character-set-server" \
    "bind-address"
  set_conf_arg "bind-address" "bind-address = 0.0.0.0" $MYSQL_CONFIG
  set_conf_arg "default-storage-engine" "default-storage-engine = InnoDB" $MYSQL_CONFIG
  set_conf_arg "collation-server" "collation-server = utf8_general_ci" $MYSQL_CONFIG
  set_conf_arg "init-connect" "init-connect = 'SET NAMES utf8'" $MYSQL_CONFIG
  set_conf_arg "character-set-server" "character-set-server = utf8" $MYSQL_CONFIG
}
