#!/bin/bash
NOVA_CONF_FILE=/etc/nova/nova.conf
PACKAGES="nova-network"

help()
{
  echo "usage: $SCRIPT_NAME $SERVICE_NAME <install|download|uninstall|config|start|stop|restart>"
}

run_service()
{
  sudo service nova-api $1
  sudo service nova-scheduler $1
  sudo service nova-conductor $1
  sudo service nova-network $1
}

run_config()
{
  edit_conf
  run_service restart
}

edit_conf()
{
  add_args_to_section $NOVA_CONF_FILE "\[DEFAULT\]" "network_api_class" \
    "security_group_api" "firewall_driver" "network_manager" "network_size" \
    "allow_same_net_traffic" "multi_host" "send_arp_for_ha" "share_dhcp_address" \
    "force_dhcp_release" "flat_network_bridge" "flat_interface" "public_interface"

  set_conf_arg "network_api_class" "network_api_class = nova.network.api.API" $NOVA_CONF_FILE
  set_conf_arg "security_group_api" "security_group_api = nova" $NOVA_CONF_FILE
  set_conf_arg "firewall_driver" "firewall_driver = nova.virt.libvirt.firewall.IptablesFirewallDriver" $NOVA_CONF_FILE
  set_conf_arg "network_manager" "network_manager = nova.network.manager.FlatDHCPManager" $NOVA_CONF_FILE
  set_conf_arg "network_size" "network_size = 254" $NOVA_CONF_FILE
  set_conf_arg "allow_same_net_traffic" "allow_same_net_traffic = False" $NOVA_CONF_FILE
  set_conf_arg "multi_host" "multi_host = True" $NOVA_CONF_FILE
  set_conf_arg "send_arp_for_ha" "send_arp_for_ha = True" $NOVA_CONF_FILE
  set_conf_arg "share_dhcp_address" "share_dhcp_address = True" $NOVA_CONF_FILE
  set_conf_arg "force_dhcp_release" "force_dhcp_release = True" $NOVA_CONF_FILE
  set_conf_arg "flat_network_bridge" "flat_network_bridge = br100" $NOVA_CONF_FILE
  set_conf_arg "flat_interface" "flat_interface = ${SET_INTERFACE_NAME}" $NOVA_CONF_FILE
  set_conf_arg "public_interface" "public_interface = ${SET_INTERFACE_NAME}" $NOVA_CONF_FILE
}

if [ $# -lt 2 ]; then
  help
elif [ "config" = $2 ]; then
  run_config
elif [ "start" = $2 -o "stop" = $2 -o "restart" = $2 ]; then
  run_service $2
elif [ "install" = $2 ]; then
  run_install $PACKAGES
elif [ "uninstall" = $2 ]; then
  run_uninstall $PACKAGES
elif [ "download" = $2 ]; then
  run_download $PACKAGES
else
  help
fi
