#!/bin/bash
import $SERVICE_OPENSTACK_IDENTITY

PACKAGE_LIST="nova-api nova-cert nova-conductor nova-consoleauth nova-novncproxy nova-scheduler python-novaclient nova-compute"
SERVICE_LIST="nova-api nova-consoleauth nova-scheduler nova-conductor nova-novncproxy nova-compute"
NOVA_CONF_FILE=/etc/nova/nova.conf
NOVA_COMPUTE_FILE=/etc/nova/nova-compute.conf

func_nova_clean()
{
  delete_user
  $SERVICE_DATABASE"_drop" $SERVICE_NAME
}

func_nova_config()
{
  $SERVICE_DATABASE"_create" $SERVICE_NAME $SET_NOVA_DBPASS
  delete_user
  create_user
  edit_conf
  sudo su -s /bin/sh -c "nova-manage db sync" $SERVICE_NAME
  func_service restart
}

edit_conf()
{
  #config NOVA_CONF_FILE
  add_args_to_section $NOVA_CONF_FILE "\[DEFAULT\]" \
    "my_ip" "vncserver_listen" "vncserver_proxyclient_address" \
    "vnc_enabled" "novncproxy_base_url"
  add_args_to_section $NOVA_CONF_FILE "\[glance\]" "host"

  set_conf_arg "my_ip" "my_ip = $SET_CONTROLLER_IP" $NOVA_CONF_FILE

  set_conf_arg "vnc_enabled" "vnc_enabled = True" $NOVA_CONF_FILE
  set_conf_arg "vncserver_listen" "vncserver_listen = $SET_CONTROLLER_IP" $NOVA_CONF_FILE
  set_conf_arg "vncserver_proxyclient_address" "vncserver_proxyclient_address = $SET_CONTROLLER_IP" $NOVA_CONF_FILE

  set_conf_arg "novncproxy_base_url" "novncproxy_base_url = http://$SET_CONTROLLER_IP:6080/vnc_auto.html" $NOVA_CONF_FILE

  set_conf_arg "host" "host = $SET_CONTROLLER_IP" $NOVA_CONF_FILE

  $SERVICE_DATABASE"_set_conf" $SERVICE_NAME $SET_GLANCE_DBPASS $NOVA_CONF_FILE
  $SERVICE_OPENSTACK_IDENTITY"_set_conf" $SERVICE_NAME $SET_CINDER_PASS $NOVA_CONF_FILE
  $SERVICE_MESSAGE_QUEUE"_set_rpc_config" $NOVA_CONF_FILE

  if [ $(egrep -c '(vmx|svm)' /proc/cpuinfo) -eq 0 ];then
    add_args_to_section $NOVA_COMPUTE_FILE "\[libvirt\]" "virt_type"
    set_conf_arg "virt_type" "virt_type = qemu" $NOVA_COMPUTE_FILE
  fi
}

create_user()
{
  load_admin_env
  $SERVICE_OPENSTACK_IDENTITY"_create_user_service" $SERVICE_NAME $SET_NOVA_PASS compute
  $SERVICE_OPENSTACK_IDENTITY"_create_endpoint" $SERVICE_NAME \
    "http://$SET_NOVA_IP:8774/v2/%\(tenant_id\)s" \
    "http://$SET_NOVA_IP:8774/v2/%\(tenant_id\)s" \
    "http://$SET_NOVA_IP:8774/v2/%\(tenant_id\)s"
}

delete_user()
{
  load_admin_env
  keystone user-delete $SERVICE_NAME
  keystone service-delete $SERVICE_NAME
}
