#!/bin/bash
PACKAGES="rabbitmq-server"

help()
{
  echo "usage: $SCRIPT_NAME $SERVICE_NAME <install|download|uninstall|config|start|stop|restart>"
}

run_config()
{
  echo "SET_RABBITMQ_PASS=$SET_RABBITMQ_PASS"
  sudo rabbitmqctl change_password guest $SET_RABBITMQ_PASS
}

run_service()
{
  sudo service rabbitmq-server $1
}

if [ $# -lt 2 ]; then
  help
elif [ "config" = $2 ]; then
  run_config
elif [ "start" = $2 -o "stop" = $2 -o "restart" = $2 ]; then
  run_service $2
elif [ "install" = $2 ]; then
  run_install $PACKAGES
elif [ "uninstall" = $2 ]; then
  run_uninstall $PACKAGES
elif [ "download" = $2 ]; then
  run_download $PACKAGES
else
  help
fi
